import Head from 'next/head'

const HomePage = () => {
    return (
        <div>
            <Head>
                <title>Devdezyn.io</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>Devdezyn.io</h1>
        </div>
    )
}

export default HomePage
